### PR TITLE
Exposing arangojs in browser bundle.

### PR DESCRIPTION
**Pull request by ciscoheat**
Fixing #245, by exposing a global `arangojs` var.

### CODE REVIEW

**Comment by pluma** [comment]
While this would work I think using the `library` and `libraryTarget` options is the more conventional solution for Webpack: http://webpack.github.io/docs/configuration.html#output-library

The expose-loader seems to be mostly for exposing libraries a bundled application depends on to the global scope so other code can access it (e.g. jquery plugins or developer tools that aren't part of the bundle).

**Comment by ciscoheat** [comment]
Yes, that looks better. I can try to make that change, but that will
probably be the end of my webpack endeavors...! I'm sure there's a method
to it, but I don't have the energy to make sense of it right now.

Den sön 19 juni 2016 17:31Alan Plum <notifications@github.com> skrev:

**Comment by ciscoheat** [comment]
It's done, using the default setting which just creates an `arangojs` var. If you'd like something else, let me know.

**Comment by pluma** [comment]
lgtm :+1:

**Pull request merged**
