### PR TITLE
Fix joinPath for relative path

### PR DESCRIPTION
**Pull request by mpv1989**

### CODE REVIEW

**Comment by pluma** [comment]
Specifically I don't think converting backslashes to slashes is expected behaviour.

**Comment by mpv1989** [comment]
@pluma `.posix.join` didn't worked. It said that `posix` is undefined.

**Comment by pluma** [comment]
@mpv1989 In the browser version or when running the test? I'm guessing the browser version always uses posix but node has had path.posix and path.win32 (and path.win32.posix, path.posix.win32 etc) since forever.

**Comment by pluma** [comment]
Yeah, that means the browser version of path.join always is path.posix.join, regardless of OS.

I'd be weak +1 on removing the test case and just using `path.join'` in `request.web.js` and using `path.posix.join` in `request.node.js`.

If you want to keep the test case, this should work in both:

```js
// util/joinPath.js
import path from "path";
const posix = path.posix || path;
export default posix.join;
```

It also leaves backslashes alone, if the user for some reason needs backslashes in their URLs.

**Pull request merged**
