### PR TITLE
Batch mode proposal

### PR DESCRIPTION
**Pull request by petitchevalroux**
I started from 3.9.1 so it's explain the conflicts ;)

Here is a proposal to implement batch mode and sample code on how to use it doc 123 exist doc 127 does not exist :
```javascript
var batch = db.getBatch();

setTimeout(function() {
    batch.collection('tests', function(err, collection) {
        if(err) {
            console.log(err);
        }
        else {
            batch.start();
            collection.document('123');
            collection.document('127');
            batch.run(function(err,results) {
                console.log('batch', results);
            });
        }
    });
}, 1000);


db.collection('tests', function(err, collection) {
    if(err) {
        throw err;
    }
    else {
        collection.document('123', function(err, document) {
            console.log('no batch', document._rev);
        });
        collection.document('127', function(err, document) {
            console.log('no batch');
        });
    }
});
```

### CODE REVIEW

**Comment by petitchevalroux** [comment]
I amended the commits and the exemple in order to clean the proposal

**Comment by pluma** [comment]
Looks intriguing but there's no way to merge this PR because of the API changes in 4.x and because the changes were made against the generated files (lib) rather than the ES6 source files (src). The generated files have been removed from the repo in 4.x to avoid problems like this.

I'm not sure how useful batch mode is considering the driver already pools connections and uses keep-alive to re-use the same connection. We should probably determine whether the performance benefits justify the added complexity -- the driver is already performing incredibly well thanks to the built-in queue.

**Comment by pcraum** [comment]
Ok no problems, I am trying to improve performance on my use case it's why I implemented this batch mode ;)

**Comment by pluma** [comment]
I'm closing this PR due to inactivity. It's unlikely batch mode will be supported in arangojs at this time.

**Pull request closed without merging**
