### PR TITLE
added tighter types

### PR DESCRIPTION
**Pull request by fceller**

### CODE REVIEW

**Comment by pluma** [comment]
The only way to deny arrays-of-arrays is to perform an explicit runtime check but I don't think we're doing that anywhere else and it wouldn't help with static analysis at write time.

BTW switching from "any" to "object" only protects against people passing strings or numbers so it's probably not worth it.

In the ArangoDB typings we made the Collection type generic so it's possible to explicitly restrict what a document looks like. That's probably the more reasonable approach as it would allow opting into a stricter type by overriding the default `any`.

**Comment by pluma** [comment]
@fceller I'll be back next week so I could look into adapting this then.

**Comment by fceller** [comment]
@pluma no runtime checks, it should "only" be for documentation and guiding users. The server will do the checks and return a suitable error message.

**Comment by pluma** [comment]
@fceller FWIW the ArangoDB typings do it this way: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/arangodb/index.d.ts#L620

Instead of `Collection` there is `Collection<T extends object = any>` (so the collection can explicitly be cast to `Collection<SomeDocumentType>` if desired) and all the methods explicitly return `Document<T>` (which adds the default metadata attributes all ArangoDB documents have if they're not already in the type).

This would be only compile/write time, not run time, and it would actually have the desired effect (because we could accept `T | T[]` and not worry about nested arrays).

**Comment by pluma** [comment]
@goedderz the change would be backwards compatible as it still defaults to `any`.

The PR as it stands is likely non-sensical as `Object | Array<Object>` would be simplified to `Object` by most code intelligence and that only means "something that inherits from Object.prototype". Also, I could likely make the change next week so unless this is extremely time critical I'd prefer delaying this.

If it's time-critical I would still request changing `Object | Array<Object>` to `object | object[]`.

**Comment by fceller** [comment]
@pluma next would be OK

**Comment by pluma** [comment]
I've imported some types from the arangodb typings I also wrote. I think it would be possible to tighten the API a bit if we drop 2.x support. Considering 2.8 has passed EOL in June last year, I think it's okay to drop 2.x support in a semver major bump.

**Pull request merged**
