### PR TITLE
Fix catch must be followed by whitespace in src/cursor.js

### PR DESCRIPTION
**Pull request by petitchevalroux**
Actually npm run lint failed during install so this pr fix the lint error in cursor.js

### CODE REVIEW

**Comment by pluma** [comment]
Eep. Thanks. I'm not sure why it's running the pre-publish hooks during install, though.

**Comment by petitchevalroux** [comment]
According to https://docs.npmjs.com/misc/scripts 
prepublish: Run BEFORE the package is published. (Also run on local npm install without any arguments.)

Don't know why :D

**Comment by pluma** [comment]
I think that refers to running `npm install` in the actual repo rather than `npm install arangojs`. The latter would have worried me as neither the tests nor the source files are in the bundle `npm install arangojs` would actually download. So it only affects maintainers/contributors.

But thanks for catching this.

**Comment by petitchevalroux** [comment]
You are right, I had the problem only running npm install from repo

**Pull request merged**
