### PR TITLE
adding example to demo the use of 'params' in transaction

### PR DESCRIPTION
**Pull request by ctmakro**
this frustrated me for about 3 hours due to lack of documentation. so let's fix it.

### CODE REVIEW

**Comment by pluma** [comment]
Hi. Sorry about the delay.

Thank you for the PR. For legal reasons we need a signed Contributor License Agreement (CLA) before we can merge your code into the project.

You can download the form from our website: https://www.arangodb.com/documents/cla.pdf

Once you've filled out and signed it, please send it to us via e-mail: cla@arangodb.com or fax: +49-221-2722999-88.

**Comment by pluma** [comment]
We don't seem to have a CLA from you on file. Could you please follow the above instructions? We can't merge the PR without a signed CLA, sadly.

**Comment by ctmakro** [comment]
sorry but just saw the email. in the middle of something. will sign ASAP.

**Comment by ctmakro** [comment]
@pluma just sent the signed CLA.

**Comment by fceller** [comment]
@pluma CLA received, @ctmakro thanks a lot

**Pull request merged**
